# Generated by Django 4.1.7 on 2023-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_dateweather_timeweather6_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWeather6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
