# Generated by Django 4.1.7 on 2023-04-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_timeweather12_timeweather15_timeweather20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather12', to='my_app.timeweather12'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather15', to='my_app.timeweather15'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather20', to='my_app.timeweather20'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather23', to='my_app.timeweather23'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather6', to='my_app.timeweather6'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather9', to='my_app.timeweather9'),
        ),
        migrations.AlterField(
            model_name='dateweather',
            name='timeWeather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather', to='my_app.timeweather'),
        ),
    ]
