# Generated by Django 4.1.7 on 2023-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_dateweather_timeweather12_dateweather_timeweather15_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='continent_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
