# Generated by Django 4.1.7 on 2023-04-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_continent_continent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dateweather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateweather', to='my_app.city'),
        ),
    ]
